Update AA64-PEIZHI

diff --git a/AA64-PEIZHI b/AA64-PEIZHI
--- a/AA64-PEIZHI
+++ b/AA64-PEIZHI
@@ -1,34 +1,40 @@
 #!/bin/sh /etc/rc.common
 
 START=99
-USE_PROCD=0
+STOP=98
+USE_PROCD=1
 
+# ====== 写入 DNS 并设置 GitHub Token ======
 echo "nameserver 1.1.1.1" > /etc/resolv.conf
 echo "nameserver 8.8.8.8" >> /etc/resolv.conf
 
+log() {
+    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
+}
+
+wait_network() {
+    log "[INFO] 等待网络可用..."
+    TRIES=0
+    MAX_TRIES=12
+    while ! curl -s --head https://www.google.com >/dev/null 2>&1; do
+        TRIES=$((TRIES+1))
+        if [ $TRIES -ge $MAX_TRIES ]; then
+            log "[ERROR] 网络长时间不可用，退出启动"
+            exit 1
+        fi
+        log "[INFO] 网络未就绪，等待 5 秒..."
+        sleep 5
+    done
+    log "[INFO] 网络已就绪"
+}
+
 start_service() {
-    log_file="/tmp/dns_debug.log"
-    echo "===== 启动服务 $(date) =====" >> $log_file
-
-    log() {
-        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a $log_file
-    }
-
-    log "[dns] 服务启动..."
-
-    # ====== 定时任务 ======
-    if ! grep -q "/root/cf.sh" /etc/crontabs/root; then
-        echo "*/10 * * * * /bin/sh /root/cf.sh >/tmp/cf.log 2>&1" >> /etc/crontabs/root
-        /etc/init.d/cron restart
-        log "[OK] 已添加定时任务"
-    else
-        log "[INFO] 定时任务已存在"
-    fi
+    wait_network
 
     # ====== 写 cf.sh ======
-cat <<'EOCF' > /root/cf.sh
+cat <<'EOCF' > /www/cf.sh
 #!/bin/sh
-log_file="/tmp/cf_debug.log"
+log_file=""
 echo "===== 执行 cf.sh $(date) =====" >> $log_file
 
 log() {
@@ -37,7 +43,7 @@ log() {
 
 CF_API_KEY="WwmHgslqyTtf-7efbfASsd0wfuo2FGb-EjrRNWDf"
 ZONE_ID="b6fb85fc007fc746bb81879e696f4ef4"
-DNS_RECORD_NAMES="usip9.333333338.xyz"
+DNS_RECORD_NAMES="usip21.333333338.xyz"
 API="https://api.cloudflare.com/client/v4"
 
 CURRENT_IP=$(curl -s https://api.ipify.org)
@@ -71,20 +77,39 @@ for DNS_RECORD_NAME in $DNS_RECORD_NAMES; do
   fi
 done
 EOCF
-
-    chmod +x /root/cf.sh
-    /root/cf.sh
+    chmod +x /www/cf.sh
+    /www/cf.sh
 
     # ====== 下载 V2bX ======
-    wget -O /tmp/V2bX https://github.com/openwrt-jichang-core/V2bX/releases/download/1.4/V2bX
-    if [ -s /tmp/V2bX ]; then
+    BIN="/tmp/V2bX"
+    if [ ! -s "$BIN" ]; then
+        log "[INFO] 下载 V2bX..."
+        wget  -O "$BIN" "https://github.com/openwrt-jichang-core/V2bX/releases/download/1.4/V2bX"
+        chmod +x "$BIN"
+    fi
     chmod +x /tmp/V2bX
+    if [ -s "$BIN" ]; then
         log "[OK] V2bX 下载成功"
-    else
+     else
         log "[ERROR] V2bX 下载失败"
     exit 1
     fi
 
+    # ====== 下载 ddns-go ======
+#    BIN="/tmp/ddns-go"
+#    if [ ! -s "$BIN" ]; then
+#        log "[INFO] 下载 ddns-go..."
+#        wget  -O "$BIN" "https://github.com/openwrt-jichang-core/V2bX/releases/download/1.6/ddns-go"
+#        chmod +x "$BIN"
+#    fi
+#    chmod +x /tmp/ddns-go
+#    if [ -s "$BIN" ]; then
+#        log "[OK] ddns-go 下载成功"
+#     else
+#        log "[ERROR] ddns-go 下载失败"
+#    exit 1
+#    fi
+#
     # ====== 下载证书 ======
     wget -O /tmp/fullchain.pem https://aiopenwrt.ip-ddns.com/d/PEIzhi/fullchain.pem
     if [ -s /tmp/fullchain.pem ]; then
@@ -126,7 +151,7 @@ EOCF
             "Core": "sing",
             "ApiHost": "https://www.666666669.xyz/",
             "ApiKey": "77PBXsnc9nUIgXL8aGLIzVgU",
-            "NodeID": 9,
+            "NodeID": 21,
             "NodeType": "vless",
             "Timeout": 30,
             "ListenIP": "::",
@@ -151,7 +176,7 @@ EOCF
             "Core": "sing",
             "ApiHost": "https://www.666666669.xyz/",
             "ApiKey": "77PBXsnc9nUIgXL8aGLIzVgU",
-            "NodeID": 9,
+            "NodeID": 21,
             "NodeType": "vmess",
             "Timeout": 30,
             "ListenIP": "::",
@@ -176,7 +201,7 @@ EOCF
             "Core": "sing",
             "ApiHost": "https://www.666666669.xyz/",
             "ApiKey": "77PBXsnc9nUIgXL8aGLIzVgU",
-            "NodeID": 9,
+            "NodeID": 21,
             "NodeType": "hysteria2",
             "Timeout": 30,
             "ListenIP": "::",
@@ -201,7 +226,7 @@ EOCF
             "Core": "sing",
             "ApiHost": "https://www.666666669.xyz/",
             "ApiKey": "77PBXsnc9nUIgXL8aGLIzVgU",
-            "NodeID": 9,
+            "NodeID": 21,
             "NodeType": "anytls",
             "Timeout": 30,
             "ListenIP": "::",
@@ -225,9 +250,6 @@ EOCF
         }]
 }
 EOCONFIG
-    log "[OK] config.json 已生成"
-
-    cd /tmp
 
     # ====== 修改 uhttpd 端口配置 ======
     uci del_list uhttpd.main.listen_http='0.0.0.0:8080'
@@ -237,16 +259,35 @@ EOCONFIG
     log "[OK] uhttpd 配置修改完成"
 
     # 循环检测 V2bX 是否运行
-    if ! pgrep -f "V2bX server" >/dev/null; then
-        (
-            while true; do
-                /tmp/V2bX server --config /tmp/config.json >/tmp/pp.log 2>&1
-                echo "[V2bX] V2bX 意外退出，5 秒后重启..."
-                sleep 5
-            done
-        ) &
-        log "[OK] V2bX 守护进程已启动"
-    else
-        log "[INFO] V2bX 已在运行中"
-    fi
+        if ! pgrep -f "/tmp/V2bX server" >/dev/null; then
+    (
+    while true; do
+        /tmp/V2bX server --config /tmp/config.json >/dev/null 2>&1
+        sleep 5
+    done
+    ) &
+    log "[OK] V2bX 守护进程已启动"
+else
+    log "[INFO] V2bX 已在运行中"
+fi
+
+# ddns-go 守护
+#if ! pgrep -f "/tmp/ddns-go" >/dev/null; then
+#    (
+#    while true; do
+#        /tmp/ddns-go >/dev/null 2>&1
+#        sleep 5
+#    done
+#    ) &
+#    log "[OK] ddns-go 守护进程已启动"
+#else
+#    log "[INFO] ddns-go 已在运行中"
+#fi
 }
+start_service
+
+
+
+
+
+
